### ISSUE TITLE
Command "pharos license assign" should have "--cluster-id" option

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#1194]

**Comment by kke** [comment]
If it takes `--cluster-id` and then requests a JWT subscription token for it, I assume enforcer should discard it because it's not for the correct cluster.

Or should it then change the `cluster-info` config map `uid` on the cluster to match? Then you could have multiple clusters with the same id and mess up something else.

**Comment by jakolehm** [comment]
The use case is mainly for air-gapped setups, maybe it should just output the kubectl command (or the k8s manifest for secret) when `--cluster-id` is given?

**Comment by kke** [comment]
So, to obtain a subscription token for another cluster.

For that, I think it needs:

- bunker: `pharos license assign --print-cluster-id` (outputs something like `12345`) (maybe this should be in some `pharos cluster-info` type of command)
- daylight: `pharos license assign --print-subcription_token --cluster-id 12345` (outputs `zxv,fshds23VVZ.xyz`
- bunker: `pharos license assign` -> `<paste `zxv,fshds23VVZ.xyz`>`

**Comment by jakolehm** [comment]
Minimum requirement is to print out license jwt token with given `--cluster-id`. We can document how to get cluster-id from a cluster and also how to put jwt token to a cluster in a bunker.
