### ISSUE TITLE
Support high-performance network plugin

### ISSUE THREAD

**Issue by jakolehm** [kontena/pharos-cluster#17]
In addition to `weave` (which is the default). Possible candidates are:

- calico
- canal
- kube-router

**Comment by SpComb** [comment]
This still needs more research in order to chose a single network provider as an alternative to weave. Intermediate notes, to be edited if needed:

* informal benchmarking with iperf on packet.net, but the results are difficult to compare without better CPU utilization metrics: https://gist.github.com/SpComb/4b5b74f0bc0217b7a9e05d0530bd3a6c
  * kube-proxy + VXLAN (Weave fastdp with trusted subnets, and also the default flannel VXLAN backend) is very sensitive to Linux softirq contention, and iperf throughput is severely limited by single-core performance...
    * enabling [Linux RPS](https://www.kernel.org/doc/Documentation/networking/scaling.txt) on the phsical network interface has a significant impact on total throughput by balancing the softirq load across multiple cores

* Weave is the only network implementation that I'm aware of which is suitable for multi-region deployments using public IP addresses across untrusted networks
  * Weave `ipsec` has very high CPU overhead (unsurprising)
  * The `weave-npc` is limited in terms of functionality 
    * https://github.com/weaveworks/weave/issues/2624 no egress policy support
    * https://github.com/weaveworks/weave/issues/3168 no `ipBlock` support (rules using `ipBlock` are handled as empty pod selectors instead, matching all inter-pod traffic)
  * Uses its own IPAM :frowning_face: 
    * more complex than the kube `podCIDR` allocation
    * problematic in terms of node removal and cleaning up addresses

* `kube-router` is equivalent to calico in terms of the resulting network topology
  * only differs in local bridge vs p2p links for pods
  * much simpler/cleaner implementation than calico (go-bgp vs confd + bird): https://github.com/cloudnativelabs/kube-router/blob/master/app/controllers/network_routes_controller.go
  * more limited in terms of configuration options
    * not going to work on e.g. DigitalOcean because it cannot be forced to use IPIP tunneling for nodes on the same subnet
  * the NPC seems to be full-featured
  * `kube-proxy --proxy-mode=ipvs` presumably means that there is no advantage to using the `kube-router` IPVS service proxy anymore
    * unless some of the advanced features like DSR from pods make sense, although I'm a little skeptical about those...
  * Not affected by the same IP-IP tunnel source address weakness as flannel (https://github.com/coreos/flannel/issues/961#issuecomment-372704073)
  * The external BGP integration is not flexible enough to support all usecases
    * e.g. announcing service externalIPs without announcing podCIDRs
      * although that usecase might be better served by https://github.com/google/metallb

* `flannel` is the reference design
  * the default VXLAN backend is mostly equivalent to weave fastdp across trusted subnets in terms of performance
  * no NPC (see canal)
  * the IP-IP backend has slightly less overhead than the default VXLAN backend
    * but it's insecure if used with public IPs: https://github.com/coreos/flannel/issues/961
  * has an experimental `IPSec` backend which would be worth testing

* Calico seems to be the most mature
  * the Kubernetes API datastore mode is still "beta"
    * but I doubt that hosting etcd for calico would be worth the effort
  * The `confd` + `bird` implementation seems like a pile of hacks compared to the go-BGP implementation in `kube-router`
    * But it works...
  * The calico NPC is probably the most advanced
    * Also the most complex rule structure
    * Uses explicit rules to whitelist IP-IP packets (ref flannel's source-address insecurity)
  * Equivalent perf with IP-IP tunneling compared to kube-router or flannel (no surprise)
  * The canal implementation also seems more complex than expected, but there may be a reason for that
    * still uses the `calico` CNI plugin instead of the `flannel` CNI plugin

TODO: further evaluate calico, or flannel + canal, in more detail
