### ISSUE TITLE
Question: How to add/remove hosts?

### ISSUE THREAD

**Issue by rubenmch** [kontena/pharos-cluster#492]
I just set up a cluster using `$ pharos-cluster up -c cluster.yml`.

What is the recommended way to add and remove hosts to the cluster?

Should I just update the cluster.yml file and execute `$ pharos-cluster up -c cluster.yml` again ?

Also, will this take down temporarily the running pods/services or will they keep running normally while the cluster is being upgraded?

**Comment by jakolehm** [comment]
> What is the recommended way to add and remove hosts to the cluster?

Adding hosts is simple, just add new hosts to the cluster.yml. 

Removal is multi-step process. You can remove host from cluster.yml but it does not actully do anything to the cluster. So basically you need to do following:
- remove host from cluster.yml
- terminate host
- remove host from kubernetes api (kubectl delete node ...)

> Also, will this take down temporarily the running pods/services or will they keep running normally while the cluster is being upgraded?

Pharos tries to minimize downtime -> it keeps user pods running even if controlplane or kubelet is upgraded.

**Comment by rubenmch** [comment]
@jakolehm Thanks

**Comment by jnummelin** [comment]
So when you had two masters, everything was fine? 

Dropping from 2 etcd nodes to single makes the etcd to break as it loses majority. With etcd it's generally advices to run 1, 3, 5,7,9 and so on peers to have maximum availability.

**Comment by sh0rez** [comment]
@jnummelin I ran the cluster with single master, thus single etcd, which was all fine.
Temporarily added a second master (to do maintenance on the old one). After things were fixed, I just believed to remove the new master as described above. Worked for kubernetes, apparently not for etcd. So how do I get etcd back to single replica?

**Comment by jnummelin** [comment]
@sh0rez I cannot reproduce since Pharos protects me:
```
==> Configure etcd member changes @ demo-pharos-master-0
RuntimeError : Cannot remove majority of etcd peers
```
I tried to go down from 2 --> 1 masters.

What were the exact steps you took to remove the second master? I'd guess you first terminated the node itself which resulted already etcd getting borked as it loses the majority.


To recover from majority loss in etcd, you need to follow the disaster recovery guide: https://coreos.com/etcd/docs/3.2.17/op-guide/recovery.html
The process itself applies, but it's somewhat complicated because Pharos sets up the etcd in a container using static pod managed by Kubelet. Here is a list of steps with which I managed to repair a borked etcd. I broke it down on purpose the same way, _I think_, by forcefully removing second node from 2 node etcd cluster.

**Note:** This worked for my exact case, no guarantee that it'll work for every case. :) If for some reason the restore fails and etcd gets up as "empty", you'll easily bork all your apps as control plane will remove all the apps, volumes etc.. In my first trial I did exactly that :D During the recovery process you might want to stop kubelets on all worker nodes so that if for some reason the control plane boots up in wrong state, kubelets will not go and bork your app pods, volumes etc.

1. Copy etcd snapshot to safe place outside of the container
- `docker cp <etcd container id>:/var/lib/etcd/member/ .` 
2. Backup and stop control plane config   
- `mkdir manifests && mv /etc/kubernetes/manifests/* manifests/` 
3. Remove all etcd data
- `rm -rf /var/lib/etcd`
4.    Run temporary etcd container just to be able to use the restore tooling. The exact parameters depend on the particular setup, you can see the correct value at you etcd static pod manifest.
- `docker run -t -i --rm -v $(pwd):/backup -w /backup -v /var/lib/:/var/lib/ registry.pharos.sh/kontenapharos/etcd:3.2.18 sh`
⁃ `ETCDCTL_API=3 etcdctl snapshot restore member/snap/db  --name=demo-pharos-master-0 --initial-cluster=demo-pharos-master-0=https://10.133.79.178:2380 --initial-cluster-token=pharos-etcd-token --initial-advertise-peer-urls=https://10.133.79.178:2380 --skip-hash-check=true --data-dir=/var/lib/etcd`
⁃ `exit`
5.    Bootup etcd
- `cp manifests/pharos-etcd.yaml /etc/kubernetes/manifests`
⁃ Ensure etcd gets up
⁃ Ensure it has all the data it used to have, i.e. to list all namespaces:
   ```
     ETCDCTL_API=3 etcdctl --endpoints=localhost:2379 --cacert=/etc/kubernetes/pki/ca.pem --cert=/etc/kubernetes/pki/etcd/client.pem --key=/etc/kubernetes/pki/etcd/client-key.pem get /registry/namespaces --prefix --keys-only
    ```
6.    Bootup Kube api
- `cp manifests/kube-apiserver.yaml /etc/kubernetes/manifests/`
⁃    Ensure Api gets up:
⁃    `kubectl get nodes`
⁃    `kubectl get namespaces`
7.    Bootup all control plane components
- `cp manifests/* /etc/kubernetes/manifests`




And yes, we clearly need better docs around adding and removing nodes to/from the cluster.

**Comment by sh0rez** [comment]
@jnummelin 
> What were the exact steps you took to remove the second master? I'd guess you first terminated the node itself which resulted already etcd getting borked as it loses the majority.

So in all details, I did the following: I own two physical hosts, a primary one and a secondary one. Both are capable of running virtual machines. Usually only the primary one is powered on. It runs 1 Master node and 3 Worker nodes.

To do maintenance on the primary one, I booted the secondary one (no vm's present on this machine at that time), created three Ubuntu Xenial VM's, added those to the `cluster.yml`, one as master and two as workers, effectively creating a cluster of 2 masters and 5 workers.
Running `pharos up` resulted in pharos provisioning the new nodes, setting up etcd and the controlplane for the second master and joining all to the cluster.

After this, I drained all worker nodes on the primary host, all pods got evicted to the 2 remaining workers. Then I drained the master on primary. After this, I shut down the primary server.

At this point, `kubectl` was already unable to return anything, I guess etcd refused operation.  
However, after maintenance was done, I brought the primary host back online, so all four old nodes got back online as well. `kubectl` started working again (probably because the etcd on the worker on primary got back), I uncordoned all nodes and drained the workers on the secondary server to take it down as it was not needed anymore. This worked without a problem, the pods evicted to the primary nodes, all seemed fine. Workers got powered off.

But after I drained the secondary master and powered this one off as well, `kubectl` refused operation again. So I brought the secondary master back online and voila! It worked again. But I don't want the secondary master to run. I want to go back to my old 3 workers, 1 master, all on the same physical host setup. (I know that this is a SPOF, I don't care as there are no critical workloads, I just want to go back there).

So in theory, my etcd is not borked, so do I really need to do this disaster recovery thing? Sounds quite risky and scary ...  
In my imagination I would just tell etcd that is alone again .. like it was for 3 months .. ?

**Comment by jnummelin** [comment]
> So in theory, my etcd is not borked

Yes, as long as you keep the second master online. :)

Pharos itself will not allow you to change the etcd cluster in a way that would compromise the majority in any way. This is purely to safeguard the etcd cluster which is pretty crucial to the cluster. As you unfortunately found out the hard way.

You probably can achieve the "back to single etcd peer" goal by managing the etcd cluster manually. Here's the official docs on it: https://coreos.com/etcd/docs/3.2.17/op-guide/runtime-configuration.html

Just remember to start with both peers (masters)  still up-and-running and make sure you've got backups for the disaster recovery if things go south.

**Comment by sh0rez** [comment]
Okay, just took a look into the etcd docs .. I guess there is a good reason not to run in single peer mode. So would it be an option to create a third master (on the primary host), temporarily having three masters (+etcd's) and then removing the secondary one? This should keep majority, but I'm unsure how consensus works then - what happens if they don't agree on something?
